import '../css/preload.css';
import '../css/elastic_grid.css';
import '../css/web-gallery.css';
import './preload';
import './vendors/modernizr.custom';
import './vendors/jquery.elastislide';
import './vendors/jquery.hoverdir';
import './vendors/jquery.elastic-grid';
import './web-design';